spring:
  cloud:
    gateway:
      routes:
        - id: java_route
          uri: http://httpbin.org
              # 时间断言
          predicates:
              - Before=2020-03-31T08:38:47+08:00
              - Method=GET
#               - Path=/2020/0912/{segment}
              - Query=name
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka

#日志
logging:
  level:
    org.springframework.cloud.gateway: debug
